# Generated by Django 5.1.3 on 2024-11-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdevice',
            name='device_type',
            field=models.CharField(choices=[('temperature_sensor', 'Cảm biến nhiệt độ, độ ẩm'), ('rain_sensor', 'Cảm biến mưa'), ('irrigation_system', 'Hệ thống tưới'), ('cover_system', 'Hệ thống che phủ')], max_length=50),
        ),
    ]
