# Generated by Django 5.1.3 on 2024-11-09 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotApp', '0002_alter_iotdevice_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSystem',
            fields=[
                ('iotdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iotApp.iotdevice')),
                ('is_active', models.BooleanField(default=False)),
            ],
            bases=('iotApp.iotdevice',),
        ),
        migrations.CreateModel(
            name='RainSensor',
            fields=[
                ('iotdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iotApp.iotdevice')),
                ('is_raining', models.BooleanField(default=False)),
            ],
            bases=('iotApp.iotdevice',),
        ),
        migrations.CreateModel(
            name='TempHumidSensor',
            fields=[
                ('iotdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iotApp.iotdevice')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
            bases=('iotApp.iotdevice',),
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='device_type',
            field=models.CharField(choices=[('TEMP_HUMID_SENSOR', 'Cảm biến nhiệt độ, độ ẩm'), ('RAIN_SENSOR', 'Cảm biến mưa'), ('CONTROL_SYSTEM', 'Hệ thống điều khiển')], max_length=50),
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
