# Generated by Django 5.1.3 on 2024-11-09 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('temperature_sensor', 'Cảm biến nhiệt độ'), ('humidity_sensor', 'Cảm biến độ ẩm'), ('rain_sensor', 'Cảm biến mưa'), ('irrigation_system', 'Hệ thống tưới'), ('cover_system', 'Hệ thống che phủ')], max_length=50)),
                ('status', models.CharField(default='inactive', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='iotApp.iotdevice')),
            ],
        ),
    ]
