# Generated by Django 5.1.3 on 2024-11-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotApp', '0003_controlsystem_rainsensor_temphumidsensor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControlSystem',
        ),
    ]
