# Generated by Django 5.1.3 on 2024-11-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotApp', '0005_remove_temphumidsensor_iotdevice_ptr_rainsensordata_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IoTDevice',
            new_name='Device',
        ),
    ]
