# Generated by Django 5.1.3 on 2024-11-13 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotApp', '0007_land_device_land'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='area',
        ),
        migrations.AlterField(
            model_name='device',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='iotApp.land'),
        ),
    ]
